# 本地测试用
version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "16379:6379"
  
  celery_webserver:
    # 镜像名称需要修改 
    image: my_celery:latest
    command: python3 -m director.cli webserver
    container_name: webserver-container
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_DB=2
      - REDIS_URL=redis://redis-container:6379
      - DIRECTOR_BROKER_URI=redis://redis-container:6379/0
      - DIRECTOR_RESULT_BACKEND_URI=redis://redis-container:6379/1
      - DIRECTOR_DATABASE_URI=postgresql://myuser:mypassword@postgres:5432/mydb
  
  celery_worker_1:
    image: my_celery:latest
    command: python3 -m director.cli celery worker --loglevel=DEBUG --queues=q1
    container_name: worker-container
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_DB=2
      - REDIS_URL=redis://redis-container:6379
      - DIRECTOR_BROKER_URI=redis://redis-container:6379/0
      - DIRECTOR_RESULT_BACKEND_URI=redis://redis-container:6379/1
      - DIRECTOR_DATABASE_URI=postgresql://myuser:mypassword@postgres:5432/mydb

volumes:
  postgres_data:
